islandora_mirador.settings:
  type: config_object
  label: 'Mirador Settings'
  mapping:
    mirador_library_installation_type:
      type: string
      label: 'Mirador library use remote'
    mirador_enabled_plugins:
      type: sequence
      label: 'Enabled Plugins'
      sequence:
        type: string
        label: 'Plugin'
    iiif_manifest_url:
      type: string
      label: 'URL pattern for IIIF manifest view'
